name: Docker Image Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: image/

      - name: Create GitHub Release with image
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.run_number }}
          files: image/my-app.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
