name: Docker Image CI preconfigured workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:image1

    - name: Run the dockerimage
      run: docker run --rm -d -p 3000:80 my-image-name:image1
    - name: Test the running server
      run: curl -I http://localhost:3000
